name = "htmldrop"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "PAGES"
id = "6087db7d282f4c27a82fe7348168c681"

[[routes]]
pattern = "baseurl.ai"
custom_domain = true
